/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sourcetek.websocketmanager.data.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.sourcetek.websocketmanager.data.model.WebSocket;
import com.liferay.sourcetek.websocketmanager.data.service.WebSocketLocalServiceUtil;

/**
 * The extended model base implementation for the WebSocket service. Represents a row in the &quot;WebSocketManager_WebSocket&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WebSocketImpl}.
 * </p>
 *
 * @author alejandro.soto
 * @see WebSocketImpl
 * @see com.liferay.sourcetek.websocketmanager.data.model.WebSocket
 * @generated
 */
public abstract class WebSocketBaseImpl extends WebSocketModelImpl
	implements WebSocket {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a web socket model instance should use the {@link WebSocket} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			WebSocketLocalServiceUtil.addWebSocket(this);
		}
		else {
			WebSocketLocalServiceUtil.updateWebSocket(this);
		}
	}
}