/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sourcetek.websocketmanager.data.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the WebSocket service. Represents a row in the &quot;WebSocketManager_WebSocket&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.sourcetek.websocketmanager.data.model.impl.WebSocketModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.sourcetek.websocketmanager.data.model.impl.WebSocketImpl}.
 * </p>
 *
 * @author alejandro.soto
 * @see WebSocket
 * @see com.liferay.sourcetek.websocketmanager.data.model.impl.WebSocketImpl
 * @see com.liferay.sourcetek.websocketmanager.data.model.impl.WebSocketModelImpl
 * @generated
 */
public interface WebSocketModel extends BaseModel<WebSocket> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a web socket model instance should use the {@link WebSocket} interface instead.
	 */

	/**
	 * Returns the primary key of this web socket.
	 *
	 * @return the primary key of this web socket
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this web socket.
	 *
	 * @param primaryKey the primary key of this web socket
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the websocket ID of this web socket.
	 *
	 * @return the websocket ID of this web socket
	 */
	public long getWebsocketId();

	/**
	 * Sets the websocket ID of this web socket.
	 *
	 * @param websocketId the websocket ID of this web socket
	 */
	public void setWebsocketId(long websocketId);

	/**
	 * Returns the name of this web socket.
	 *
	 * @return the name of this web socket
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this web socket.
	 *
	 * @param name the name of this web socket
	 */
	public void setName(String name);

	/**
	 * Returns the description of this web socket.
	 *
	 * @return the description of this web socket
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this web socket.
	 *
	 * @param description the description of this web socket
	 */
	public void setDescription(String description);

	/**
	 * Returns the port of this web socket.
	 *
	 * @return the port of this web socket
	 */
	public int getPort();

	/**
	 * Sets the port of this web socket.
	 *
	 * @param port the port of this web socket
	 */
	public void setPort(int port);

	/**
	 * Returns the thread_id of this web socket.
	 *
	 * @return the thread_id of this web socket
	 */
	@AutoEscape
	public String getThread_id();

	/**
	 * Sets the thread_id of this web socket.
	 *
	 * @param thread_id the thread_id of this web socket
	 */
	public void setThread_id(String thread_id);

	/**
	 * Returns the active of this web socket.
	 *
	 * @return the active of this web socket
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this web socket is active.
	 *
	 * @return <code>true</code> if this web socket is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this web socket is active.
	 *
	 * @param active the active of this web socket
	 */
	public void setActive(boolean active);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(WebSocket webSocket);

	public int hashCode();

	public CacheModel<WebSocket> toCacheModel();

	public WebSocket toEscapedModel();

	public String toString();

	public String toXmlString();
}