/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sourcetek.websocketmanager.data.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.search.Indexer;
import com.liferay.portal.kernel.search.IndexerRegistryUtil;
import com.liferay.portal.kernel.search.SearchException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.liferay.sourcetek.websocketmanager.data.model.WebSocket;
import com.liferay.sourcetek.websocketmanager.data.service.WebSocketLocalService;
import com.liferay.sourcetek.websocketmanager.data.service.WebSocketService;
import com.liferay.sourcetek.websocketmanager.data.service.persistence.WebSocketPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the web socket local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.sourcetek.websocketmanager.data.service.impl.WebSocketLocalServiceImpl}.
 * </p>
 *
 * @author alejandro.soto
 * @see com.liferay.sourcetek.websocketmanager.data.service.impl.WebSocketLocalServiceImpl
 * @see com.liferay.sourcetek.websocketmanager.data.service.WebSocketLocalServiceUtil
 * @generated
 */
public abstract class WebSocketLocalServiceBaseImpl
	implements WebSocketLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.sourcetek.websocketmanager.data.service.WebSocketLocalServiceUtil} to access the web socket local service.
	 */

	/**
	 * Adds the web socket to the database. Also notifies the appropriate model listeners.
	 *
	 * @param webSocket the web socket
	 * @return the web socket that was added
	 * @throws SystemException if a system exception occurred
	 */
	public WebSocket addWebSocket(WebSocket webSocket)
		throws SystemException {
		webSocket.setNew(true);

		webSocket = webSocketPersistence.update(webSocket, false);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(webSocket);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return webSocket;
	}

	/**
	 * Creates a new web socket with the primary key. Does not add the web socket to the database.
	 *
	 * @param websocketId the primary key for the new web socket
	 * @return the new web socket
	 */
	public WebSocket createWebSocket(long websocketId) {
		return webSocketPersistence.create(websocketId);
	}

	/**
	 * Deletes the web socket with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param websocketId the primary key of the web socket
	 * @throws PortalException if a web socket with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteWebSocket(long websocketId)
		throws PortalException, SystemException {
		WebSocket webSocket = webSocketPersistence.remove(websocketId);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(webSocket);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Deletes the web socket from the database. Also notifies the appropriate model listeners.
	 *
	 * @param webSocket the web socket
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteWebSocket(WebSocket webSocket) throws SystemException {
		webSocketPersistence.remove(webSocket);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(webSocket);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return webSocketPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return webSocketPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return webSocketPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return webSocketPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public WebSocket fetchWebSocket(long websocketId) throws SystemException {
		return webSocketPersistence.fetchByPrimaryKey(websocketId);
	}

	/**
	 * Returns the web socket with the primary key.
	 *
	 * @param websocketId the primary key of the web socket
	 * @return the web socket
	 * @throws PortalException if a web socket with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public WebSocket getWebSocket(long websocketId)
		throws PortalException, SystemException {
		return webSocketPersistence.findByPrimaryKey(websocketId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return webSocketPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the web sockets.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of web sockets
	 * @param end the upper bound of the range of web sockets (not inclusive)
	 * @return the range of web sockets
	 * @throws SystemException if a system exception occurred
	 */
	public List<WebSocket> getWebSockets(int start, int end)
		throws SystemException {
		return webSocketPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of web sockets.
	 *
	 * @return the number of web sockets
	 * @throws SystemException if a system exception occurred
	 */
	public int getWebSocketsCount() throws SystemException {
		return webSocketPersistence.countAll();
	}

	/**
	 * Updates the web socket in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param webSocket the web socket
	 * @return the web socket that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public WebSocket updateWebSocket(WebSocket webSocket)
		throws SystemException {
		return updateWebSocket(webSocket, true);
	}

	/**
	 * Updates the web socket in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param webSocket the web socket
	 * @param merge whether to merge the web socket with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the web socket that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public WebSocket updateWebSocket(WebSocket webSocket, boolean merge)
		throws SystemException {
		webSocket.setNew(false);

		webSocket = webSocketPersistence.update(webSocket, merge);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(webSocket);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return webSocket;
	}

	/**
	 * Returns the web socket local service.
	 *
	 * @return the web socket local service
	 */
	public WebSocketLocalService getWebSocketLocalService() {
		return webSocketLocalService;
	}

	/**
	 * Sets the web socket local service.
	 *
	 * @param webSocketLocalService the web socket local service
	 */
	public void setWebSocketLocalService(
		WebSocketLocalService webSocketLocalService) {
		this.webSocketLocalService = webSocketLocalService;
	}

	/**
	 * Returns the web socket remote service.
	 *
	 * @return the web socket remote service
	 */
	public WebSocketService getWebSocketService() {
		return webSocketService;
	}

	/**
	 * Sets the web socket remote service.
	 *
	 * @param webSocketService the web socket remote service
	 */
	public void setWebSocketService(WebSocketService webSocketService) {
		this.webSocketService = webSocketService;
	}

	/**
	 * Returns the web socket persistence.
	 *
	 * @return the web socket persistence
	 */
	public WebSocketPersistence getWebSocketPersistence() {
		return webSocketPersistence;
	}

	/**
	 * Sets the web socket persistence.
	 *
	 * @param webSocketPersistence the web socket persistence
	 */
	public void setWebSocketPersistence(
		WebSocketPersistence webSocketPersistence) {
		this.webSocketPersistence = webSocketPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.liferay.sourcetek.websocketmanager.data.model.WebSocket",
			webSocketLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.liferay.sourcetek.websocketmanager.data.model.WebSocket");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	protected ClassLoader getClassLoader() {
		Class<?> clazz = getClass();

		return clazz.getClassLoader();
	}

	protected Class<?> getModelClass() {
		return WebSocket.class;
	}

	protected String getModelClassName() {
		return WebSocket.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = webSocketPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = WebSocketLocalService.class)
	protected WebSocketLocalService webSocketLocalService;
	@BeanReference(type = WebSocketService.class)
	protected WebSocketService webSocketService;
	@BeanReference(type = WebSocketPersistence.class)
	protected WebSocketPersistence webSocketPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private static Log _log = LogFactoryUtil.getLog(WebSocketLocalServiceBaseImpl.class);
	private String _beanIdentifier;
}